version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: shell-scripts/stop_server.sh
      timeout: 45
      runas: ec2-user
  BeforeInstall:
    - location: shell-scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  DownloadBundle:

  Install:

  AfterInstall:
    - location: shell-scripts/change_permissions.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: shell-scripts/start_server.sh
      timeout: 45
      runas: ec2-user
