#!/bin/bash  
sudo yum update -y  
sudo amazon-linux-extras install epel -y
sudo yum install stress -y
sudo yum install httpd -y
sudo service httpd start
sudo chkconfig httpd on
sudo service httpd stop
sudo usermod -a -G apache ec2-user
sudo chown -R ec2-user:apache /var/www
sudo chmod 2775 /var/www
find /var/www -type d -exec sudo chmod 2775 {} \;
wget https://aws-codedeploy-us-west-2.s3.us-west-2.amazonaws.com/latest/install
chmod +x ./install
sudo ./install auto
sudo service codedeploy-agent status
sudo service codedeploy-agent start
sudo service codedeploy-agent status

